### ISSUE TITLE
launching several instances with diferent parameters from outside arrays

### ISSUE THREAD

**Issue by fullmooninu** [echocat/puppet-mongodb#53]
Guys, can you help me with this? I have this global array of strings, $mongo_instances, defined by someone else, and i'm supposed to to create a mongod resource for each string in that array.
Problem is, the port also changes.
Before using your module I solved this problem with a define that looped over the array and used an .erb template that create an adequate mongo .conf file for each mongod.
I was wondering if you know a better way of doing this.

Pseudo code:

```puppet
#these are the global arrays i get from someone else:
$mongo_instances = ['mongo1','mongo2','mongo3']
$mongo_ports = [27017,27018,27019]

for $i=0; $i<3; $i++ {

#create a resource like so

  mongodb::mongod { $mongo_instances[$i]:
    mongod_instance => $mongo_instances[$i],
    mongod_port     => $mongo_ports[$i],
    mongod_replSet  => 'samerepleset',
  }

}
```

or actually, more close to what I have is:

```puppet
$mongo_instances = ['mongo1','mongo2','mongo3']
$mongo_iport = 27017

for $i=0; $i<count($mongo_instances); $i++ {

#create a resource like so

  mongodb::mongod { $mongo_instances[$i]:
    mongod_instance => $mongo_instances[$i],
    mongod_port     => $mongo_iport+$i,
    mongod_replSet  => 'samerepleset',
  }
 }
```
I know current mongo doesn't have straight forward iteration. Right now I'm experimenting with this:

https://docs.puppetlabs.com/references/latest/function.html#createresources

So I was wondering how to do accomplish the above, and also another question:

what is the diference between the mongod resource name and the mongod_instance resource parameter? Your docs say it's a description, but, does it actually go somewhere in mongo .conf or is it just used internally?

**Comment by fullmooninu** [comment]
"what is the diference between the mongod resource name and the mongod_instance resource parameter? Your docs say it's a description, but, does it actually go somewhere in mongo .conf or is it just used internally?"  =) just this bit?

**Comment by dwerder** [comment]
The documentation is correct. If the mongod_instance is not set explicitly , then its the same as the resources name. And it is used for the init sccript names and log file names and so on. You need that for cases like this

```puppet
mongodb::mongod {'this is my cluser node 1':
  mongod_instances => 'node1'
}
```
