### ISSUE TITLE
debian repo gpg key is too short

### ISSUE THREAD

**Issue by richardrasu** [echocat/puppet-mongodb#59]
Hi,

We see a lot of the following messages on our machines;

[Add key: 7F0CEB10 from Apt::Source 10gen]) The id should be a full fingerprint (40 characters), see README.

This is due to not using the full finger print, which in this case is: 492EAFE8CD016A07919F1D2B9ECBEC467F0CEB10

Is this enough info for you, or do I need to fork the repo, make the change, issue a PR etc?

Cheers

R.

**Comment by richardrasu** [comment]
@dwerder Man that was nice & fast. You _rock_ :) Thanks!

**Comment by cdenneen** [comment]
@dwerder can you push new version up to forge?
