### ISSUE TITLE
Invalid resource type logrotate::rule

### ISSUE THREAD

**Issue by bobweston** [echocat/puppet-mongodb#61]
I'm trying to get the module working (using ref: 21b6930d1b1ecf44abeceb0c4ebc34573f9b8273). But when I try to provision the server, it errors out with the following:

==> db01: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type logrotate::rule at /tmp/vagrant-puppet/modules-078fcdc8fc841e4b19c52c75025d7110/mongodb/manifests/logrotate.pp:29 on node ctcinteract-db01.ap.org
==> db01: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type logrotate::rule at /tmp/vagrant-puppet/modules-078fcdc8fc841e4b19c52c75025d7110/mongodb/manifests/logrotate.pp:29 on node ctcinteract-db01.ap.org

I'm running ubuntu 12.04 with puppet 3.8.3

Any help is appreciated.

**Comment by dwerder** [comment]
Did you try it with the commit before that change?

**Comment by bobweston** [comment]
Rolling back to an earlier version eliminated that error.

**Comment by gpenaud** [comment]
I had that error ; i fixed it with adding  "rodjek/logrotate" module in my Puppetfile (managed with r10k)
Maybe could you set this in requirement part of your documentation ?

**Comment by dwerder** [comment]
The module requierement are already documented in metadata.json, .fixtures.yaml and in README.md at the section for requierements.
